### ISSUE TITLE
Support for ALE

### ISSUE THREAD

**Issue by qrevel** [juliosueiras/vim-terraform-completion#29]
Hi,

Could you add support for [ALE](https://github.com/w0rp/ale)?

Thanks

**Comment by juliosueiras** [comment]
No problem, will look into these two days

**Comment by juliosueiras** [comment]
Can close for now due to support for tflint is part of ale now, might reopen if some one want native terraform validate and my custom validate to be use with ALE

**Comment by sebiwi** [comment]
Hi, this would actually be pretty good to have. 

I'm under the impression that ALE linting just uses tflint, which doesn't actually outputs anything when the file syntax is broken, for example. The behaviour from the asciinema clip on the readme is pretty cool, and I'd love to have it integrated with ALE.

Thanks!

**Comment by faraazkhan** [comment]
+1 it would be really cool to get ALE support for `terraform validate` and `tffilter` in here
