### ISSUE TITLE
Allow disabling/configuring of key mappings

### ISSUE THREAD

**Issue by bzub** [juliosueiras/vim-terraform-completion#31]
Some of these key mappings conflict with my setup. Would be good to be able to disable/configure them via variables.

https://github.com/juliosueiras/vim-terraform-completion/blob/71a7edc03cf63db9c375ac58c4f4e7a24bae1639/ftplugin/terraform.vim#L43

**Comment by shinzui** [comment]
This badly breaks my mappings also.

**Comment by juliosueiras** [comment]
Done, use `let g:terraform_completion_keys = 1` to enable it, or 0 to disable it
