### ISSUE TITLE
Doesn't work with neovim (raw / deoplete / YCM)

### ISSUE THREAD

**Issue by DavidUser** [juliosueiras/vim-terraform-completion#37]
## Using just neovim

[![asciicast](https://asciinema.org/a/hc59NBMblz2jlbQvN29Nr0wJJ.png)](https://asciinema.org/a/hc59NBMblz2jlbQvN29Nr0wJJ)

This source code example is [here](https://github.com/DavidUser/test-vim-terraform-complete-neovim)

## Using neovim + deoplete

[![asciicast](https://asciinema.org/a/spJ0BFSsQltCyZUJE59ilFvsg.png)](https://asciinema.org/a/spJ0BFSsQltCyZUJE59ilFvsg)

This source code example is [here](https://github.com/DavidUser/test-vim-terraform-complete-neovim-deoplete)

## Using [YCM](https://github.com/Valloric/YouCompleteMe)

[![asciicast](https://asciinema.org/a/hSUbaIDyhw4LXukiqgrvzDqdK.png)](https://asciinema.org/a/hSUbaIDyhw4LXukiqgrvzDqdK)

When i type to complete just `0` pop up to completion.
This is on my machine.

**Comment by juliosueiras** [comment]
Please provide more description

**Comment by juliosueiras** [comment]
what is the output for `:set omnifunc` ?

**Comment by DavidUser** [comment]
omnifunc=terraformcomplete#Complete

**Comment by DavidUser** [comment]
So, I remove all YCM, install deoplete, install this plugin and doesn't work just seems like trying found some completion and doesn't work.
I'll put my build on dockerfile to show exactly what is happening

**Comment by DavidUser** [comment]
Done, I update the description and put examples using distinct configuration with neo**vim**.

**Comment by juliosueiras** [comment]
for deoplete, try adding `let g:deoplete#enable_at_startup = 1` to your ~/.config/nvim/init.vim

**Comment by DavidUser** [comment]
This is already in use and doesn't work like you can see here https://github.com/DavidUser/test-vim-terraform-complete-neovim-deoplete/blob/master/.config/nvim/init.vim#L20

**Comment by juliosueiras** [comment]
found the issue, the fix is that fedora ruby does not come with json gem, so installing json gem will fix

added the info on README

**Comment by DavidUser** [comment]
Perfect, it falls well!
