### ISSUE TITLE
Docker build incomplete

### ISSUE THREAD

**Issue by DavidUser** [juliosueiras/vim-terraform-completion#38]
![image](https://user-images.githubusercontent.com/6628028/37374747-5b34dd40-26fb-11e8-8be4-47837cda1b85.png)

**Comment by juliosueiras** [comment]
the vader.vim is part of travis.yml

`git clone https://github.com/junegunn/vader.vim`

**Comment by DavidUser** [comment]
Ok, it's a good idea put this on docker Dockerfile.
