### ISSUE TITLE
E10: \ should be followed by /, ? or & line 1242:

### ISSUE THREAD

**Issue by barthalion** [juliosueiras/vim-terraform-completion#41]
After installation of `hashivim/vim-terraform` and `juliosueiras/vim-terraform-completion`, Vim throws list of errors at startup:

```
E10: \ should be followed by /, ? or &
line 1243:
E10: \ should be followed by /, ? or &
line 1244:
E10: \ should be followed by /, ? or &
line 1245:
E10: \ should be followed by /, ? or &
line 1246:
E10: \ should be followed by /, ? or &
line 1247:
E10: \ should be followed by /, ? or &
line 1248:
E10: \ should be followed by /, ? or &
line 1249:
E10: \ should be followed by /, ? or &
```

It repeats up to number 1270, next occurences are 1281, 1283, 1287 and 1289.

hashivim/vim-terraform is at `76799270813db362b13a56f26cd34f668e9e17a4`
vim-terraform-completion is at `b451f39c1ad5649bf277cc7a366e2fdf2afcb987`
vim 8.0.1542

It doesn't happen when only one of these two is enabled. Any idea what's going on or how to make this report more useful?

**Comment by barthalion** [comment]
Never mind, looks like I made a mistake – it happens only when `vim-terraform` is loaded. I will report it there.

Sorry for the noise.

**Comment by juliosueiras** [comment]
no problem
