### ISSUE TITLE
How to to make it work with neovim?

### ISSUE THREAD

**Issue by mcanevet** [juliosueiras/vim-terraform-completion#44]
I'm using the neovim package v0.2.2 from Debian sid and it looks like it does not have `ruby/dyn` enabled. At least `echo has('ruby/dyn')` returns `0`. So this plugin does not work because of [this](https://github.com/juliosueiras/vim-terraform-completion/blob/master/autoload/terraformcomplete.vim#L1-L3).
According to `:help feature-compile`, "Nvim always includes ALL features, in contrast to Vim", so I can't figure out why `echo has('ruby/dyn')` does not return `1`.

**Comment by mcanevet** [comment]
Never mind I misread the code...

**Comment by juliosueiras** [comment]
hi, just want to ask, can you explain what was the issue?

**Comment by juliosueiras** [comment]
no problem

**Comment by esn89** [comment]
I have a similar problem to you.  I have installed the neovim as a ruby gem and it shows 0.

However, I am still unable to get it to work with neovim.
I have copied the config exactly.  Any ideas?

**Comment by esn89** [comment]
Hey @juliosueiras 

Thanks for your reply, I have tried the new deoplete but got this error instead:
```
or detected while processing /Users/esn89/.config/nvim/plugged/vim-terraform-completion/autoload/terraformcomplete.vim:                                                     
line    6:                                                                                                                                                                      
E121: Undefined variable: deoplete#omni_patterns                                                                                                                                
Press ENTER or type command to continue   ```

Here is my :checkhealth
```

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#LanguageClient#check
========================================================================
  - OK: binary found: /Users/esn89/.config/nvim/plugged/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.119 59f0299e8f7d7edd0653b5fc005eec74c4bf4aba

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.15
  - INFO: python2-neovim version: 0.2.6
  - OK: Latest python2-neovim is installed: 0.2.6

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.7.0
  - INFO: python3-neovim version: 0.2.6
  - OK: Latest python3-neovim is installed: 0.2.6

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
  - INFO: Host: /Users/esn89/.gem/ruby/2.3.0/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.7.1

## Node.js provider (optional)
  - INFO: Node.js: v10.9.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

```

**Comment by juliosueiras** [comment]
@esn89 can you try with the new config ?(just updated the deoplete config on README)

**Comment by esn89** [comment]
It works, thank you.

However, when I type "res" resource, I get this red error message, any ideas?

https://i.imgur.com/22CJxr8.png

I am using this config: 
```
let g:deoplete#omni_patterns = {}

call deoplete#custom#option('omni_patterns', {
\ 'complete_method': 'omnifunc',
\ 'terraform': '[^ *\t"{=$]\w*',
\})

call deoplete#initialize()```

**Comment by esn89** [comment]
ah, i see.  thanks for your reply, and sorry for being so bothersome :)
