### ISSUE TITLE
Add support for Ale

### ISSUE THREAD

**Issue by sebiwi** [juliosueiras/vim-terraform-completion#52]
Hi.

Thank you for this amazing plugin.

It would be great to have [Ale](https://github.com/w0rp/ale) support for linting purposes.

Thanks!

**Comment by juliosueiras** [comment]
will double check

**Comment by diegombeltran** [comment]
This would be great!

**Comment by eredi93** [comment]
It'd be great to get this. @juliosueiras any chance you could get a chance to work on this any time soon 🙏 
I'm not very familiar with vimscript or Vim plugins in general, but i'm more than happy to give it a go if you could give me a few pointers 😄

**Comment by juliosueiras** [comment]
K, I will take a quick look at ALE later today

**Comment by eredi93** [comment]
Awesome! thanks @juliosueiras 🙇

**Comment by sandangel** [comment]
@juliosueiras is it possible to add [coc.nvim](https://github.com/neoclide/coc.nvim) support as well? I don't know how hard it's to integrate with coc.nvim instead of deoplete

**Comment by juliosueiras** [comment]
@sandangel I am actually started developing an LSP plugin for terraform https://twitter.com/juliosueiras/status/1124814166085312512 =) , it will support most of HCL2 features and will add more LSP features(document lookup, highlight,etc)

**Comment by juliosueiras** [comment]
Released =) https://github.com/juliosueiras/terraform-lsp

**Comment by sandangel** [comment]
@juliosueiras great, thanks a lot. I will take a look.

**Comment by johnmaguire** [comment]
It looks like syntastic is now deprecated - https://github.com/vim-syntastic/syntastic

Is it possible to use terraform-lsp with Vim today?

edit: NVM, found the docs - https://github.com/juliosueiras/terraform-lsp/blob/master/docs/editors/vim.md
