### ISSUE TITLE
Plugin broken in vim 8.1

### ISSUE THREAD

**Issue by barlik** [juliosueiras/vim-terraform-completion#59]
I'm running vim 8.1-996 and the plugin is returning an error when I try to auto-complete. The problem seems to be use of `a:` prefixes for the variables inside `Complete` function. Those prefixed are only meant to be used for the function arguments.  I assume that ViM 8.1 is now more strict about using them and thus returns an E461 error.

```
Error detected while processing function terraformcomplete#Complete:         
line   11:
E461: Illegal variable name: a:res
```

**Comment by juliosueiras** [comment]
@barlik thanks, will double check for that

**Comment by juliosueiras** [comment]
hi, can you pull the change and check now? there might be some issue(it was a quick fix)

**Comment by barlik** [comment]
@juliosueiras, I confirm that it's fixed now. Thank you for the quick response.

**Comment by barlik** [comment]
Unrelated question. Have you had any thought about implementing the completion as a language server? Not that I particularly care about other editors, but implementing a language server could get much more people involved with the project and thus everybody benefits.

**Comment by juliosueiras** [comment]
@barlik no problem, that is a valid question, I am mostly waiting for HCL 2.0 to become GA, since I am definitely planning of create a LSP version of this plugin

**Comment by barlik** [comment]
That's amazing, I'm looking forward to it. Thanks again for writing this plugin and fixing the problem.
