### ISSUE TITLE
Considering using Data from intellij-hcl as the scrapper

### ISSUE THREAD

**Issue by juliosueiras** [juliosueiras/vim-terraform-completion#6]
Might try out using data of intellij-hcl as the basing point for scrapping data for autocompletion

[reference](https://github.com/VladRassokhin/intellij-hcl/tree/master/res/terraform/model/providers)

**Comment by VladRassokhin** [comment]
You may use [special branch of Terraform](https://github.com/VladRassokhin/terraform/tree/f-export-schema-master), which generates that data. Though I'm rebasing it on newest TF releases with forced push.

**Comment by juliosueiras** [comment]
Thanks!!, I will look into it

**Comment by juliosueiras** [comment]
now the issue is how the attribute data is being pull
