### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by ccampanale** [juliosueiras/vim-terraform-completion#9]
Please consider including a list of dependencies in your documentation for other's as ignorant as I was about vim plugins before today. 

  - [vim-terraform](https://github.com/hashivim/vim-terraform)
  - [vim-syntastic](https://github.com/vim-syntastic/syntastic)

I confirmed vim was setup with `+ruby/dyn` and moved my couple modules over to `vim-plug` and was pulling my hair out trying to determine why it still wasn't working. I do believe the two plugins above were key to prevent further frustration. (That said, I'm still not entirely sure my linting is working after installing `tflint`...)

Also, a short blurb about example configuration and usage would be nice. (I personally found installing [vim-supertab](https://github.com/ervandew/supertab) quite helpful.) Either way, usage examples explaining how your are using the plugin as seen in your awesome Asciinemas presentations would be a perfect addition.

Thanks for the awesome module; looking forward to continued development! :)

**Comment by juliosueiras** [comment]
Thanks for the suggestion, I am thinking using a docker container(quick one) to mimic a user env so I can make sure a brand new vim can use this plugin without too much hiccups

**Comment by juliosueiras** [comment]
Is the current one working? I added a minimal configuration on README.md

**Comment by ccampanale** [comment]
The updated README looks great! Thanks!

I started the Docker test you mentioned on this PR: https://github.com/juliosueiras/vim-terraform-completion/pull/14
